
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:27 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:27 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.43.34808/bin/Hostx64/x64/cl.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) C/C++ Optimizing Compiler Version 19.43.34808 for x64
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      CMakeCXXCompilerId.cpp
      Microsoft (R) Incremental Linker Version 14.43.34808.0
      Copyright (C) Microsoft Corporation.  All rights reserved.
      
      /out:CMakeCXXCompilerId.exe 
      CMakeCXXCompilerId.obj 
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.obj"
      
      The CXX compiler identification is MSVC, found in:
        C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/3.26.4/CompilerIdCXX/CMakeCXXCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:1153 (message)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:221 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:27 (project)"
    message: |
      Detecting CXX compiler /showIncludes prefix:
        main.c
        Note: including file: C:\\temp\\PA213\\framework\\cmake-build-debug\\CMakeFiles\\ShowIncludes\\foo.h
        
      Found prefix "Note: including file: "
  -
    kind: "try_compile-v1"
    backtrace:
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:27 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ptn6xy"
      binary: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ptn6xy"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_INSTALLED_DIR: "C:/temp/PA213/framework/cmake-build-debug/vcpkg_installed"
      VCPKG_PREFER_SYSTEM_LIBS: "OFF"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/temp/PA213/framework/ext/vcpkg"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ptn6xy
        
        Run Build Command(s):K:/CLion 2023.2.2/bin/ninja/win/x64/ninja.exe -v cmTC_e01cc && [1/2] C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\\cmTC_e01cc.dir\\CMakeCXXCompilerABI.cpp.obj /FdCMakeFiles\\cmTC_e01cc.dir\\ /FS -c "\\\\home.fi.muni.cz\\data-xstruha1\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        [2/2] cmd.exe /C "cd . && "\\\\home.fi.muni.cz\\data-xstruha1\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_e01cc.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_e01cc.dir\\CMakeCXXCompilerABI.cpp.obj  /out:cmTC_e01cc.exe /implib:cmTC_e01cc.lib /pdb:cmTC_e01cc.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CheckCXXSourceCompiles.cmake:76 (cmake_check_source_compiles)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/FindThreads.cmake:99 (CHECK_CXX_SOURCE_COMPILES)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/FindThreads.cmake:163 (_threads_check_libc)"
      - "ext/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "cmake-build-debug/vcpkg_installed/x64-windows/share/glfw3/glfw3Config.cmake:2 (find_dependency)"
      - "ext/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)"
      - "framework/core/CMakeLists.txt:19 (find_package)"
    checks:
      - "Performing Test CMAKE_HAVE_LIBC_PTHREAD"
    directories:
      source: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-mn8ud5"
      binary: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-mn8ud5"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_INSTALLED_DIR: "C:/temp/PA213/framework/cmake-build-debug/vcpkg_installed"
      VCPKG_PREFER_SYSTEM_LIBS: "OFF"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/temp/PA213/framework/ext/vcpkg"
    buildResult:
      variable: "CMAKE_HAVE_LIBC_PTHREAD"
      cached: true
      stdout: |
        Change Dir: C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-mn8ud5
        
        Run Build Command(s):K:/CLion 2023.2.2/bin/ninja/win/x64/ninja.exe -v cmTC_f6e05 && [1/2] C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP -DCMAKE_HAVE_LIBC_PTHREAD  /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\\cmTC_f6e05.dir\\src.cxx.obj /FdCMakeFiles\\cmTC_f6e05.dir\\ /FS -c C:\\temp\\PA213\\framework\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-mn8ud5\\src.cxx
        FAILED: CMakeFiles/cmTC_f6e05.dir/src.cxx.obj 
        C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP -DCMAKE_HAVE_LIBC_PTHREAD  /DWIN32 /D_WINDOWS /W3 /GR /EHsc  /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\\cmTC_f6e05.dir\\src.cxx.obj /FdCMakeFiles\\cmTC_f6e05.dir\\ /FS -c C:\\temp\\PA213\\framework\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-mn8ud5\\src.cxx
        C:\\temp\\PA213\\framework\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-mn8ud5\\src.cxx(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CheckLibraryExists.cmake:71 (try_compile)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/FindThreads.cmake:112 (CHECK_LIBRARY_EXISTS)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/FindThreads.cmake:175 (_threads_check_lib)"
      - "ext/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "cmake-build-debug/vcpkg_installed/x64-windows/share/glfw3/glfw3Config.cmake:2 (find_dependency)"
      - "ext/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)"
      - "framework/core/CMakeLists.txt:19 (find_package)"
    checks:
      - "Looking for pthread_create in pthreads"
    directories:
      source: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-bad0q6"
      binary: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-bad0q6"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_INSTALLED_DIR: "C:/temp/PA213/framework/cmake-build-debug/vcpkg_installed"
      VCPKG_PREFER_SYSTEM_LIBS: "OFF"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/temp/PA213/framework/ext/vcpkg"
    buildResult:
      variable: "CMAKE_HAVE_PTHREADS_CREATE"
      cached: true
      stdout: |
        Change Dir: C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-bad0q6
        
        Run Build Command(s):K:/CLion 2023.2.2/bin/ninja/win/x64/ninja.exe -v cmTC_25d14 && [1/2] C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc -DCHECK_FUNCTION_EXISTS=pthread_create /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\\cmTC_25d14.dir\\CheckFunctionExists.cxx.obj /FdCMakeFiles\\cmTC_25d14.dir\\ /FS -c C:\\temp\\PA213\\framework\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-bad0q6\\CheckFunctionExists.cxx
        [2/2] cmd.exe /C "cd . && "\\\\home.fi.muni.cz\\data-xstruha1\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_25d14.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_25d14.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_25d14.exe /implib:cmTC_25d14.lib /pdb:cmTC_25d14.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthreads.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        FAILED: cmTC_25d14.exe 
        cmd.exe /C "cd . && "\\\\home.fi.muni.cz\\data-xstruha1\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_25d14.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_25d14.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_25d14.exe /implib:cmTC_25d14.lib /pdb:cmTC_25d14.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthreads.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        LINK Pass 1: command "C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_25d14.dir\\CheckFunctionExists.cxx.obj /out:cmTC_25d14.exe /implib:cmTC_25d14.lib /pdb:cmTC_25d14.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console pthreads.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_25d14.dir/intermediate.manifest CMakeFiles\\cmTC_25d14.dir/manifest.res" failed (exit code 1104) with the following output:
        LINK : fatal error LNK1104: cannot open file 'pthreads.lib'
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CheckLibraryExists.cmake:71 (try_compile)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/FindThreads.cmake:112 (CHECK_LIBRARY_EXISTS)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/FindThreads.cmake:176 (_threads_check_lib)"
      - "ext/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)"
      - "//home.fi.muni.cz/data-xstruha1/CLion 2023.2.2/bin/cmake/win/x64/share/cmake-3.26/Modules/CMakeFindDependencyMacro.cmake:76 (find_package)"
      - "cmake-build-debug/vcpkg_installed/x64-windows/share/glfw3/glfw3Config.cmake:2 (find_dependency)"
      - "ext/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)"
      - "framework/core/CMakeLists.txt:19 (find_package)"
    checks:
      - "Looking for pthread_create in pthread"
    directories:
      source: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8skav2"
      binary: "C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8skav2"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
      VCPKG_INSTALLED_DIR: "C:/temp/PA213/framework/cmake-build-debug/vcpkg_installed"
      VCPKG_PREFER_SYSTEM_LIBS: "OFF"
      VCPKG_TARGET_TRIPLET: "x64-windows"
      Z_VCPKG_ROOT_DIR: "C:/temp/PA213/framework/ext/vcpkg"
    buildResult:
      variable: "CMAKE_HAVE_PTHREAD_CREATE"
      cached: true
      stdout: |
        Change Dir: C:/temp/PA213/framework/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-8skav2
        
        Run Build Command(s):K:/CLion 2023.2.2/bin/ninja/win/x64/ninja.exe -v cmTC_2cb1f && [1/2] C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\cl.exe  /nologo /TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc -DCHECK_FUNCTION_EXISTS=pthread_create /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\\cmTC_2cb1f.dir\\CheckFunctionExists.cxx.obj /FdCMakeFiles\\cmTC_2cb1f.dir\\ /FS -c C:\\temp\\PA213\\framework\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-8skav2\\CheckFunctionExists.cxx
        [2/2] cmd.exe /C "cd . && "\\\\home.fi.muni.cz\\data-xstruha1\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_2cb1f.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_2cb1f.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_2cb1f.exe /implib:cmTC_2cb1f.lib /pdb:cmTC_2cb1f.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthread.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        FAILED: cmTC_2cb1f.exe 
        cmd.exe /C "cd . && "\\\\home.fi.muni.cz\\data-xstruha1\\CLion 2023.2.2\\bin\\cmake\\win\\x64\\bin\\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\\cmTC_2cb1f.dir --rc=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\rc.exe --mt=C:\\PROGRA~2\\WI3CF2~1\\10\\bin\\100226~1.0\\x64\\mt.exe --manifests  -- C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_2cb1f.dir\\CheckFunctionExists.cxx.obj  /out:cmTC_2cb1f.exe /implib:cmTC_2cb1f.lib /pdb:cmTC_2cb1f.pdb /version:0.0 /machine:x64  /debug /INCREMENTAL /subsystem:console  pthread.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
        LINK Pass 1: command "C:\\PROGRA~1\\MIB055~1\\2022\\COMMUN~1\\VC\\Tools\\MSVC\\1443~1.348\\bin\\Hostx64\\x64\\link.exe /nologo CMakeFiles\\cmTC_2cb1f.dir\\CheckFunctionExists.cxx.obj /out:cmTC_2cb1f.exe /implib:cmTC_2cb1f.lib /pdb:cmTC_2cb1f.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console pthread.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\\cmTC_2cb1f.dir/intermediate.manifest CMakeFiles\\cmTC_2cb1f.dir/manifest.res" failed (exit code 1104) with the following output:
        LINK : fatal error LNK1104: cannot open file 'pthread.lib'
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
